Repository AlaaZorkane/silentcorner-bot, pull requests merged in 2020-02, with the labels that each got.

#1 recoding added
  index.js
Labels: 7amda 🍋, enhancement

#5 Syncing with dev branch
  index.js
Labels: bug, enhancement

#6 Randomise trash
  modules/Control.js
Labels: command, enhancement

#8 Bolissi/Trash command improved
  index.js
  modules/Control.js
  modules/Store.js
Labels: command, enhancement, module
